name: Api
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test and Deploy Lambda functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test functions
        run: pytest

      - name: Package functions code
        run: cd profile; zip -r ../visitor_record_visit.zip .; cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy package functions to s3
        run: aws s3 cp visitor_record_visit.zip ${{ secrets.S3_BUCKET_URI }}
